# Generated by Django 2.1.1 on 2020-03-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.BigIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('need', models.FloatField(default=1)),
                ('amount', models.DecimalField(decimal_places=5, max_digits=6)),
                ('main_product_code', models.IntegerField()),
                ('time', models.DecimalField(decimal_places=2, max_digits=4)),
                ('operation_name', models.ForeignKey(on_delete=models.SET('DELETED'), to='pieces.Operation')),
                ('parent_product_code', models.ForeignKey(on_delete=models.SET('DELETED'), to='pieces.Piece')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='piece',
            name='station_code',
            field=models.ForeignKey(on_delete=models.SET('DELETED'), to='pieces.Station'),
        ),
    ]
