# Generated by Django 2.1.1 on 2020-03-12 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0002_auto_20200313_0317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piece',
            name='operation_name',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='station_code',
        ),
        migrations.DeleteModel(
            name='Piece',
        ),
    ]
