# Generated by Django 2.1.1 on 2020-03-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0003_auto_20200313_0327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.BigIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=5, default=1, max_digits=6)),
                ('main_product_code', models.IntegerField()),
                ('parent_product_code', models.BigIntegerField()),
                ('time', models.DecimalField(decimal_places=2, max_digits=4)),
                ('operation_name', models.ForeignKey(on_delete=models.SET('DELETED'), to='pieces.Operation')),
                ('station_code', models.ForeignKey(on_delete=models.SET('DELETED'), to='pieces.Station')),
            ],
        ),
    ]
