# Generated by Django 2.1.1 on 2020-03-13 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0004_piece'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='parent_product_code',
            field=models.ForeignKey(on_delete=models.SET('DELETED'), to='pieces.Piece'),
        ),
    ]
